#!/bin/bash
/alx-system_engineering-devops/:
total 4
drwxr-xr-x 4 root root   43 Mar  9 02:07 .
drwxr-xr-x 1 root root  172 Mar  8 00:37 ..
drwxr-xr-x 2 root root 4096 Mar  9 09:49 0x00-shell_basics
drwxr-xr-x 8 root root  166 Mar  9 09:50 .git

/alx-system_engineering-devops/0x00-shell_basics/:
total 64
drwxr-xr-x 2 root root 4096 Mar  9 09:49 .
drwxr-xr-x 4 root root   43 Mar  9 02:07 ..
-rwxr--r-- 1 root root   16 Mar  8 00:59 0-current_working_directory
-rwxr--r-- 1 root root   24 Mar  8 22:58 10-back
-rwxr--r-- 1 root root  108 Mar  9 09:49 11-lists
-rwxr--r-- 1 root root   31 Mar  8 23:26 12-file_type
-rwxr--r-- 1 root root   76 Mar  8 15:40 14-copy_html
-rwxr--r-- 1 root root   15 Mar  8 03:32 1-listit
-rwxr--r-- 1 root root   21 Mar  8 09:55 2-bring_me_home
-rwxr--r-- 1 root root   18 Mar  8 10:49 3-listfiles
-rwxr--r-- 1 root root   19 Mar  8 10:59 4-listmorefiles
-rwxr--r-- 1 root root   19 Mar  8 12:51 5-listfilesdigitonly
-rwxr--r-- 1 root root   42 Mar  8 13:01 6-firstdirectory
-rwxr--r-- 1 root root   50 Mar  8 13:11 7-movethatfile
-rwxr--r-- 1 root root   45 Mar  8 13:21 8-firstdelete
-rwxr--r-- 1 root root   42 Mar  8 13:30 9-firstdirdeletion
-rw-r--r-- 1 root root    0 Mar  8 15:34 file_0.html
-rw-r--r-- 1 root root    0 Mar  8 15:34 file_1.html
-rw-r--r-- 1 root root   20 Mar  8 10:35 README.md

/boot/:
total 0
drwxr-xr-x 2 root root   6 Apr 15  2020 .
drwxr-xr-x 1 root root 172 Mar  8 00:37 ..
